=== jl0325/brayan_coffe/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (address, contact, hours)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT hours (weekday, weekend)>
<!ELEMENT weekday (#PCDATA)>
<!ELEMENT weekend (#PCDATA)>

=== jl0325/brayan_coffe/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
    <branch>
        <address>76 Devonshire St, Surry Hills NSW</address>
        <contact>02 9211 1234</contact>
        <hours>
            <weekday>Mon - Fri: 6:00 to 14:30</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </hours>
    </branch>
    <branch>
        <address>451 Pitt St, Haymarket Sydney, NSW</address>
        <contact>02 9262 5678</contact>
        <hours>
            <weekday>Mon - Fri: 6:00 to 16:00</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </hours>
    </branch>
    <branch>
        <address>31 Alfred Street, Circular Quay, NSW</address>
        <contact>02 8971 9101</contact>
        <hours>
            <weekday>Mon - Fri: 6:00 to 16:00</weekday>
            <weekend>Sat-Sun: 7:00 to 15:00</weekend>
        </hours>
    </branch>
</branches>
